jobs:
  agent-embed-issue:
    if: contains(github.event.comment.body, 'solution:')
    permissions:
      contents: read
      issues: read
    runs-on:
    - ubuntu-latest
    steps:
    - id: agent_secrets
      uses: hashicorp/vault-action@v4
      with:
        method: userpass
        password: ${{ secrets.VAULT_PASSWORD }}
        secrets: servc/data/iac/servc agent-auth-token | AGENT_TOKEN ;
        url: ${{ secrets.VAULT_ADDR }}
        username: ${{ secrets.VAULT_USERNAME }}
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Send to embeddings
      uses: https://git.yusufali.ca/actions/embed-issues@main
      with:
        api_token: ${{ steps.agent_secrets.outputs.AGENT_TOKEN }}
        api_url: ${{ secrets.AGENT_API_URL }}
name: Send Issues to VectorDB
'on':
  issue_comment:
    types:
    - created
    - edited
