jobs:
  dispatch:
    if: contains(github.event.comment.body, '@bot')
    permissions:
      contents: read
      issues: read
    runs-on:
    - ubuntu-latest
    steps:
    - id: agent_secrets
      uses: hashicorp/vault-action@v4
      with:
        method: userpass
        password: ${{ secrets.VAULT_PASSWORD }}
        secrets: servc/data/iac/servc agent-auth-token | AGENT_TOKEN ;
        url: ${{ secrets.VAULT_ADDR }}
        username: ${{ secrets.VAULT_USERNAME }}
    - id: gitea_secrets
      uses: hashicorp/vault-action@v4
      with:
        method: userpass
        password: ${{ secrets.VAULT_PASSWORD }}
        secrets: servc/data/iac/gitea token | PAT_TOKEN ;
        url: ${{ secrets.VAULT_ADDR }}
        username: ${{ secrets.VAULT_USERNAME }}
    - env:
        GITHUB_TOKEN: ${{ steps.gitea_secrets.outputs.PAT_TOKEN }}
      name: Send task to coding agent
      uses: https://git.yusufali.ca/actions/issue-codebot@main
      with:
        api_token: ${{ steps.agent_secrets.outputs.AGENT_TOKEN }}
        api_url: ${{ secrets.AGENT_API_URL }}
        bot_route: agent-bot
        debug: false
name: Send Tasks to Agent
'on':
  issue_comment:
    types:
    - created
    - edited
